import os

# SentriAI Mini Shared Configuration
COOLDOWN_DEFAULT_SECONDS = float(os.getenv("COOLDOWN_DEFAULT_SECONDS", 10.0))
OCR_CONFIDENCE_THRESHOLD = float(os.getenv("OCR_CONFIDENCE_THRESHOLD", 0.85))
EMBEDDING_SIMILARITY_THRESHOLD = float(os.getenv("EMBEDDING_SIMILARITY_THRESHOLD", 0.82))
CLIP_DURATION_SECONDS = 10
